DEBUG = True
# SECRET_KEY is generated by os.urandom(24).
# SECRET_KEY = '\xf7\xf4\x9bb\xd7\xa8\xdb\xee\x9f\xe3\x98SR\xda\xb0@\xb7\x12\xa4uB\xda\xa3\x1b'
# STRIPE_API_KEY = ''
JSON_AS_ASCII = False

URL = 'http://localhost:5000'